### PR TITLE
Security: update various dependencies

### PR DESCRIPTION
**Pull request by aluccaroni**
Update dependencies to clear security warnings and CVEs

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by aluccaroni** [comment]
Since the update of Zookeeper to 3.6.3 we are failing in the same place: BrokerHTTPClientWithZKDiscoveryTest.test:59

**Review by eolivelli — COMMENTED** [review]
With the upgrade from 3.5 to 3.6 of zookeeper you must include explicitly snappy and probably other libs in order to let zookeeper server start.

In 3.6 zookeeper maven dependency are for clients and not tuned for running the zk server.
We need the server in the tests and also IIRC we need it for bin/server zookeeper start

**Comment by aluccaroni** [comment]
> With the upgrade from 3.5 to 3.6 of zookeeper you must include explicitly snappy and probably other libs in order to let zookeeper server start.
> 
> In 3.6 zookeeper maven dependency are for clients and not tuned for running the zk server. We need the server in the tests and also IIRC we need it for bin/server zookeeper start

I'm rollbacking the ZK update. I will take a look to the 3.5 -> 3.6 upgrade path after we merge this pull.

**Review by hamadodene — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

btw ZooKeeper 3.5 is almost dead :-)

**Pull request merged**
